apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - name: java-demo
        image: <YOUR-Docker-Registry>/java-demo:latest
        ports:
        - containerPort: 8080
